config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'
  resources :categories do
    resources :comments, only: [:create]
  end
  resources :articles do
    resources :comments, only: [:create]
  end

  resources :comments do
    resources :comments
  end

  root 'home#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :category
  has_many :comments, as: :commentable, dependent: :destroy
  validates :name, presence: true, format: {
    with: /[A-ZА-Я][A-ZА-Яa-zа-я]+\s+[A-ZА-Яa-zа-я]{2,}\s*\.\s*(?!.)/,
    message: 'must contain two words(mininmum 2 symbols) and \'.\', first word start with capital letter'
  }
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :articles, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  validates :name, presence: true, format: { with: /[A-ZА-Я][A-ZА-Яa-zа-я]+\s+[A-ZА-Яa-zа-я]{2,}\s*\.\s*(?!.)/, message: "must contain two words(mininmum 2 symbols) and '.', first word start with capital letter" }
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :comentable, polymorphic: true, optional: true
  has_many :comments, as: :commentable
  validates :content, presence: true
  after_create_commit { RenderCommentJob.perform_later self }

  def author
    user.email
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_data, only: %i[show edit update destroy]

  def index
    current_user
    @articles = Article.all.order(created_at: :desc)
  end

  def show
    @comments = @article.comments
    @category = @article.category
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to @category, notice: 'Article was successfully destroyed.' }
    end
  end

  private

  def set_data
    @article = Article.friendly.find(params[:id])
    @category = @article.category
  end

  def article_params
    params.require(:article).permit(:name, :content, :category_id)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all.order(created_at: :desc)
  end

  def show
    @comments = @category.comments.order(created_at: :desc)
    @articles = @category.articles.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :get_item, only: [:create]

  def create
    @comment = @item.comments.new comment_params
    @comment.user_id = current_user.id
    @comment.save
    # if @comment.save
    #   ActionCable.server.broadcast('comments_channel',
    #     comment: @comment.content,
    #     author: @comment.author
    #   )
    head :ok
    # end
  end

  private

  def get_item
    params.each do |name, _value|
      if name =~ /(.+)_id$/
        @item = Regexp.last_match(1).classify.constantize.friendly.find(params[name.to_sym])
      end
    end
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @categories = Category.order(created_at: :desc).last(2)
    @articles = Article.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/articles/_article.html.erb
<div class="articles_article">
  <h2>
    <%= article.name%>
  </h2>
  <div class="content">
    <p>
      <%= article.content%>
    </p>
    <div class="info">
     <p>Created at: <%= article.created_at.strftime("%Y-%m-%d") %></p>
     <p>Category: <%= article.category.name %></p>
    </div>
  </div>

  <div class="actions">
    <%= link_to 'Show', article_path(article) %>
    <%= link_to 'Edit', edit_article_path(article) %>
    <%= link_to 'Destroy', article, method: :delete,remote: true, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <%= render 'components/errors', item: article%>
  <p>
    <%= form.text_field :name, placeholder: "Name"%>
  </p>
  <p>
    <%= form.text_area :content, placeholder: "Description", rows: 6%>
  </p>
  <p>
    <%= form.select(:category_id, Category.all.map{|i|[i.name, i.id]}) %>
  </p>
  <div class="submit">
    <%= form.button 'Create', type: :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="articles_article">
  <h1>Editing Article</h1>
  <%= render 'form', article: @article %>
  <div class="actions">
    <%= link_to  "Back", :back %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="articles">
  <h1>Articles</h1>
  <div class="articles_wrap">
    <%= render @articles %>
    <div class="actions">
      <%= link_to 'New Article', new_article_path %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="articles_article">
  <h1>New Article</h1>
  <%= render 'form', article: @article %>
  <div class="actions">
    <%= link_to  "Back", :back %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="articles_article">
  <h2>
    <%= @article.name %>
  </h2>
  <div class="content">
    <p>
      <%= @article.content %>
    </p>
  </div>
  <div class="actions">
    <%= link_to  "To Category", @category %>
    <%= link_to 'Edit', edit_article_path(@article) %>
    <%= link_to 'Destroy', @article, method: :delete,remote: true, data: { confirm: 'Are you sure?' } %>
  </div>
	<div class="comments" style="<%= 'display: none' unless @comments.present? %>">
    <%= render 'comments/list', item: @article%>
	</div>
  <%= render 'comments/form', item: @article %>
</div>

app/views/categories/_category.html.erb
<div class="categories_category">
  <h2>
    <%= category.name%>
  </h2>
  <div class="content">
    <p>
      <%= category.description%>
    </p>
    <div class="info">
      <p>Created at: <%= category.created_at.strftime("%Y-%m-%d") %></p>
    </div>
  </div>

  <div class="actions">
    <%= link_to 'Show', category_path(category)  %>
    <%= link_to 'Edit', edit_category_path(category) %>
    <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <%= render 'components/errors', item: category%>
  <p>
    <%= form.text_field :name, placeholder: "Name"%>
  </p>
  <p>
    <%= form.text_area :description, placeholder: "Description", rows: 6%>
  </p>
  <div class="submit">
    <%= form.button :button, type: :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="categories_category">
  <h1>Editing Category</h1>
  <%= render 'form', category: @category %>
  <div class="actions">
    <%= link_to  "Back", :back %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="categories">
  <h1>Categories</h1>
  <div class="categories_wrap">
    <%= render @categories %>
    <div class="actions">
      <%= link_to 'New Category', new_category_path %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="categories_category">
  <h1>New Category</h1>
  <%= render 'form', category: @category %>
  <div class="actions">
    <%= link_to  "Back", :back %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="categories_category">
  <h2>
    <%= @category.name%>
  </h2>
  <div class="content">
    <p>
      <%= @category.description%>
    </p>
  </div>
  <div class="actions">
    <%= link_to 'Back', :back%>
    <%= link_to 'Edit', edit_category_path(@category) %>
    <%= link_to 'Destroy', @category, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>

  <div class="comments" style="<%= 'display: none' unless @comments.present? %>">
    <%= render 'comments/list',item: @category%>
	</div>
  <%= render 'comments/form', item: @category %>

  <div class="articles">
    <%if @articles.present?%>
    <h2>Articles</h2>
    <div class="articles_wrap">
      <%= render @articles %>
    </div>
    <%end%>
    <div class="actions">
      <%= link_to 'New Article', new_article_path %>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="comments_comment">
	<p>
		<strong>Commenter:</strong>
		<%= comment.author %>
	</p>
	<%if comment.content.present?%>
	<p>
		<strong>Comment:</strong>
		<%= comment.content %>
	</p>
	<%end%>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [item, item.comments.new]) do |form| %>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content, rows: 6 %>
  </p>
  <p>
    <%= form.button 'Create', type: :submit %>
  </p>
<% end %>

app/views/comments/_list.html.erb
<h3>Comments</h3>
<div class="comments_wrap" id="comments_wrap">
  <%= render @comments %>
</div>

app/views/home/index.html.erb
<div class="home">
  <% if @categories.present? %>
    <h2><%= link_to  "Categories", categories_path %></h2>
    <div class="home_wrap">
      <%= render @categories %>
    </div>
  <% end %>
  <% if @articles.present? %>
    <h2><%= link_to  "Articles", articles_path %></h2>
    <div class="home_wrap">
      <%= render  @articles %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlog</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Neucha|Pacifico&amp;subset=cyrillic" rel="stylesheet">
  </head>
  <body>
    <%= render "components/header" %>
    <%= render "components/main" %>
    <%= render "components/footer"%>
  </body>
</html>